### ISSUE TITLE
Make it work with any setup

### ISSUE THREAD

**Issue by IceDBorn** [IceDBorn/rtssh#5]
Find a way for it to work with any output of "sensors -j"

**Comment by telepresencebot2** [comment]
Would this encompass things like CPU frequency reporting?

**Comment by IceDBorn** [comment]
@telepresencebot2 No, I think that "sensors -j" only displays temps. I'll have to use a different tool on the linux side to get the cpu's frequency. Don't worry though, as soon as I find a way to get the temps from any system, I'll work on freqs too.

**Comment by IceDBorn** [comment]
@telepresencebot2 Check #15
